/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul10part2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author ACER
 */
public class SIM extends javax.swing.JFrame {

    /**
     * Creates new form SIM
     */
    public SIM() {
        initComponents();
        getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ShowdataMenu = new javax.swing.JMenuItem();
        InsertdataMenu = new javax.swing.JMenuItem();
        UpdatedataMenu = new javax.swing.JMenuItem();
        DeletedataMenu = new javax.swing.JMenuItem();
        ExitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        ShowdataMenu.setText("Show Data");
        ShowdataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowdataMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ShowdataMenu);

        InsertdataMenu.setText("Insert Data");
        InsertdataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertdataMenuActionPerformed(evt);
            }
        });
        jMenu1.add(InsertdataMenu);

        UpdatedataMenu.setText("Update Data ");
        UpdatedataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatedataMenuActionPerformed(evt);
            }
        });
        jMenu1.add(UpdatedataMenu);

        DeletedataMenu.setText("Delete Data ");
        DeletedataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletedataMenuActionPerformed(evt);
            }
        });
        jMenu1.add(DeletedataMenu);

        ExitMenu.setText("EXIT");
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ExitMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowdataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowdataMenuActionPerformed
        // TODO add your handling code here:
        showData show = new showData();
        show.setVisible(true);
       
    }//GEN-LAST:event_ShowdataMenuActionPerformed

    private void InsertdataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertdataMenuActionPerformed
        // TODO add your handling code here:
        insertData insert = new insertData();
        insert.setVisible(true);
    }//GEN-LAST:event_InsertdataMenuActionPerformed

    private void UpdatedataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatedataMenuActionPerformed
        // TODO add your handling code here:
        updateData update = new updateData();
        update.setVisible(true);
    }//GEN-LAST:event_UpdatedataMenuActionPerformed

    private void DeletedataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletedataMenuActionPerformed
        // TODO add your handling code here:
        deleteData delete = new deleteData();
        delete.setVisible(true);
    }//GEN-LAST:event_DeletedataMenuActionPerformed

    private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_ExitMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIM().setVisible(true);
                
            }
        });
        
     
    }
    
    public Connection getConnection() {
        String host = "localhost";
        String port = "1521";
        String db = "xe";
        String usr = "SYSTEM";
        String pwd = "SYSTEM";

        Connection conn = null;

        try {
            // Memuat driver JDBC Oracle
            Class.forName("oracle.jdbc.driver.OracleDriver");

            // Membuat koneksi
            conn = DriverManager.getConnection("jdbc:oracle:thin:@" + host + ":" + port + ":" + db, usr, pwd);

            System.out.println("Koneksi ke database berhasil terbentuk");
        } catch (ClassNotFoundException ex) {
            System.out.println("Maaf, driver class tidak ditemukan");
            System.out.println(ex.getMessage());
        } catch (SQLException ex) {
            System.out.println("Maaf, koneksi tidak berhasil.");
            System.out.println(ex.getMessage());
        }

        return conn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DeletedataMenu;
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenuItem InsertdataMenu;
    private javax.swing.JMenuItem ShowdataMenu;
    private javax.swing.JMenuItem UpdatedataMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
